(ql:quickload '(:cl-ppcre :fset))

(defun day11 ()
  (let ((network (loop :with network := (fset:empty-map (fset:empty-set))
                       :for line :in (uiop:read-file-lines #P"./11.txt")
                       :for (source outputs) := (ppcre:split ": " line)
                       :do (loop :with result := (fset:empty-set)
                                 :for output :in (ppcre:split " " outputs)
                                 :do (fset:includef result (intern output))
                                 :finally (fset:includef network
                                                         (intern source)
                                                         result))
                       :finally (return network))))
    (labels ((find-node (path node)
               (fset:find-if (lambda (x) (eql x node)) path))
             (count-paths (source target)
               (loop :with candidates := (fset:seq (fset:seq source))
                     :and paths := (fset:empty-set)
                     :for path := (fset:pop-first candidates)
                     :while path
                     :for last-node := (fset:last path)
                     :for outputs := (fset:lookup network last-node)
                     :do (fset:do-set (next-node outputs)
                           (let ((next-path (fset:with-last path next-node)))
                             (if (eql next-node target)
                                 (fset:includef paths next-path)
                                 (unless (find-node path next-node)
                                   (fset:push-last candidates next-path)))))
                     :finally (return (fset:size paths)))))
      (count-paths '|you| '|out|))))
