(ql:quickload :fset)

(defun day06 (is-part-two)
  (let ((school (fset:empty-bag)))
    (dolist (timer (uiop:split-string (uiop:read-file-line #P"./06.txt")
                                      :separator '(#\,)))
      (fset:includef school (parse-integer timer)))
    (labels ((tick (school)
               (let ((result (fset:empty-bag)))
                 (fset:do-bag-pairs (timer n school result)
                   (if (zerop timer)
                       (progn (fset:includef result 6 n)
                              (fset:includef result 8 n))
                       (fset:includef result (1- timer) n))))))
      (dotimes (_ (if is-part-two 256 80) (fset:size school))
        (setf school (tick school))))))
